### ISSUE TITLE
Needs a .babelrc file and missing build directory

### ISSUE THREAD

**Issue by forgo** [mweibel/react-date-picker#2]
I was unable to build based off a similar fork. I thought I would add that I needed to add the following to a ".babelrc" file to get the `npm run build` to work, for example:

`{ "presets": ["react"] }`

Otherwise, the build would trip up when it encountered JSX syntax in the many ".js" files. For example `<div {...`

Also, I noticed that I cannot run `npm run dev` which is looking for webpack.config.js under a `build/` directory which does not exist in this fork and does not seem to be generated otherwise.

Did you run across this build directory when you forked, or were you only able to find the source that comes from NPM as I did?

**Comment by mweibel** [comment]
Yeah I basicly just copied what I had in my node modules folder after installing it. A real fork was unfortunately not possible because the original repo is gone. 
I didn't try to build it myself yet, though.

I'll be happy to accept a PR.

Another thing: I've seen Jetbrains releasing some components and [their date picker looks quite good](http://www.jetbrains.org/ring-ui/date-picker.html). Maybe worth a try (just as a thought, I didn't try it myself yet).

**Comment by mweibel** [comment]
@forgo I tried other date pickers, this one is still the best to me. 
I worked now on https://github.com/mweibel/react-date-picker/pull/3/files and will test that now in the project I use it with. If everything works I'll merge that PR and publish the package as `react-date-picker-reborn@6.0.0`

Feel free to help!

**Comment by forgo** [comment]
I know this is late, but thanks for the follow-up. I was unaware of Jetbrain's "Ring UI". This is a great resource. I believe we later upgraded our components to use [AirBnB's date picker](https://github.com/airbnb/react-dates)

I feel it's better to drop the late 'react-date-picker' as there is a lot of momentum behind newer components.

I have seen good progress toward other re-usable components in React, such as [react-select](https://react-select.com/), which is highly configurable, conform to better practices, and attempt to be 508 accessible. I think that one even has an experimental date picker built in.

**Comment by mweibel** [comment]
I've used https://github.com/Hanse/react-calendar since. Exactly what I need since it's very customizable :) -> Not going to continue on this repo.
